Ingredients
To make a dough-
3-4 medium potatoes boiled and mashed
1 medium onion chopped finely
1 tsp ginger garlic paste
3/4 tsp crushed red chillies
1 tbsp chopped coriander leaves
1/4 tsp garam masala
salt to taste
3 tbsp bread crumbs
2 tbsp cornflour
1/2 tsp lemon juice
For maida slurry-
3 tbsp maida
water as required to make a slurry
for crumb mix
1/8-1/4 cup bread crumbs
1/8 tsp mixed herbs
1/2 tsp red chilli crushed
Other ingredients-
Oil for deep frying